Update ch5-test01

diff --git a/.github/workflows/poi-ch4-cd.yml b/.github/workflows/poi-ch4-cd.yml
--- a/.github/workflows/poi-ch4-cd.yml
+++ b/.github/workflows/poi-ch4-cd.yml
@@ -9,7 +9,7 @@ env:
   repository: ganrad/openhack-devops-team-20/api-poi
   docker_path: apis/poi/web
   staging_url: https://openhackvm13xxh0poi-staging.azurewebsites.net/api/healthcheck/poi
-  prod_url: https://openhackvm13xxh0poi.azurewebsites.net/
+  prod_url: https://openhackvm13xxh0poi.azurewebsites.net/api/healthcheck/poi
   resource_group: openhackvm13xxh0rg
   webapp_name: openhackvm13xxh0poi
   build_name: POI 
@@ -21,6 +21,7 @@ on:
     branches: [ master ]
     paths: 
       - apis/poi/**
+      - .github/workflows/poi-ch4-cd.yml
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -111,14 +112,13 @@ jobs:
     runs-on: ubuntu-latest
     needs: deploy_staging
     steps:      
-    - name: Web Validate 
+    - name: Validate web service in staging 
       run: |
         while [ true ]; do
            result=`curl -s -o /dev/null -w "%{http_code}" $staging_url`
            if [ -z $result ]; then
               echo "Status from healthcheck endpoint is empty!"
               exit 1
-              # break
            fi
            echo "Status from healthcheck endpoint : $result"
            if [ $result == "200" ]; then
@@ -130,6 +130,97 @@ jobs:
            fi
         done 
 
+    - uses: actions/github-script@0.9.0
+      if: failure()
+      with:
+        github-token: ${{secrets.GITHUB_TOKEN}}
+        script: |
+          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
+          github.issues.create({
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
+            body: body
+          });
+  
+  # Swap the slots : staging to production (CH:5 starts here)
+  swap_slots:
+    if: github.ref == 'refs/heads/master'
+    runs-on: ubuntu-latest
+    needs: validate_staging
+    steps:
+    - name: Azure authentication
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.AZURE_CREDENTIALS  }}
+
+    - name: Swap staging to production
+      run: |
+        az webapp deployment slot swap --name $webapp_name --resource-group $resource_group --slot staging --target-slot production
+    - uses: actions/github-script@0.9.0
+      if: failure()
+      with:
+        github-token: ${{secrets.GITHUB_TOKEN}}
+        script: |
+          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
+          github.issues.create({
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
+            body: body
+          });
+  
+  # Validate the app deployment in production slot after swapping
+  validate_production:
+    if: github.ref == 'refs/heads/master'
+    runs-on: ubuntu-latest
+    needs: swap_slots
+    steps:      
+    - name: Validate web service in production 
+      run: |
+        while [ true ]; do
+           result=`curl -s -o /dev/null -w "%{http_code}" $prod_url`
+           if [ -z $result ]; then
+              echo "Status from healthcheck endpoint is empty!"
+              exit 1
+           fi
+           echo "Status from healthcheck endpoint : $result"
+           if [ $result == "200" ]; then
+              echo "Web service in production seems to be running OK!"
+              break
+           else
+              echo "Web service is not ready, sleeping 5 seconds ..."
+              sleep 5
+           fi
+        done
+        
+    - uses: actions/github-script@0.9.0
+      if: failure()
+      with:
+        github-token: ${{secrets.GITHUB_TOKEN}}
+        script: |
+          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
+          github.issues.create({
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
+            body: body
+          });
+
+  # Rollback staging into production on failure!
+  roll_back:
+    if: failure()
+    runs-on: ubuntu-latest
+    needs: validate_production
+    steps:
+    - name: Azure authentication
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.AZURE_CREDENTIALS  }}
+
+    - name: Swap production and staging
+      run: |
+        az webapp deployment slot swap --name $webapp_name --resource-group $resource_group --slot staging --target-slot production 
     - uses: actions/github-script@0.9.0
       if: failure()
       with:
